// Code generated by reset generator. DO NOT EDIT.

package model

func (rs *Storage) Reset() {
	if rs == nil {
		return
	}

	rs.UUID = ""
	rs.ShortURL = ""
	rs.OriginalURL = ""
	rs.UserID = ""
	rs.IsDeleted = false
}
